name: Matt Long
url: https://www.burythehammer.com
description: Matt Long's homepage
permalink: /blog/:title
markdown: kramdown
lsi: true
include: [".well-known"]
exclude: [
  Gemfile, Gemfile.lock, nginx.conf, CNAME, nginx.common.conf, README.md,
  post-receive.sh, CLAUDE.md
]
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      toc: true

sass:
  style: :compressed
